### ISSUE TITLE
Keeping Contact

### ISSUE THREAD

**Issue by BrainBacon** [Beg-in/Fritz#3]
Hey all,

I would like to continue keeping touch and developing this library further. I propose we all either connect via Slack, or we start a group hangout. I would like to know your guys' opinion on either of these options!

Hangouts: [add me on G+ ](https://plus.google.com/110342829010121213850)
Slack: [email me](mailto:brian@beg.in)

Also you should all add yourselves as contributors to `package.json`!

**Comment by BrainBacon** [comment]
- [x] @dstratossong
- [x] @LOZORD 
- [ ] @itsmichaelwang
- [x] @nodox

**Comment by nodox** [comment]
Email sent. I've also been curious of gitter. I've seen it integrated in README files all around github. Maybe we can add that as a way for others to join us.

**Comment by LOZORD** [comment]
:+1: for gitter (instead of Slack(?))

**Comment by BrainBacon** [comment]
I set up a Gitter. Should we still connect via Hangouts?

**Comment by BrainBacon** [comment]
https://gitter.im/Beg-in/Fritz?utm_source=share-link&utm_medium=link&utm_campaign=share-link
