### ISSUE TITLE
Versioning Hooks

### ISSUE THREAD

**Issue by BrainBacon** [Beg-in/Fritz#5]
We need `npm version` hooks that will run the following tasks:
- [ ] `gulp test` - verify build is stable
- [ ] `gulp changelog` - update the `CHANGELOG.md` file
- [ ] `gulp docs` - update the `README.md` file (if necessary)
- [ ] add and commit changed files
- [ ] push the changes and tags to Github

[See the documentation for the `npm version` command](https://docs.npmjs.com/cli/version)

**Comment by nodox** [comment]
Do you want this to happen pre or post version. Are we going to use the auto-incrementor provided by npm version [arg_name]. Also do you want to commit and push to development branch?

**Comment by BrainBacon** [comment]
Yeah the plan is to use the auto-incrementor.
1. test should be preversion as I believe a failure will cancel the version command.
2. Docs and changelog should be version since we want to add these files to the commit.
3. The push should be branch-agnostic for support with forks.

**Comment by BrainBacon** [comment]
Looks good. Feel free to close this!
